name = "AppliedNativeSARSOP"
uuid = "7d2d7113-a6e2-4323-be53-22784c9d2988"
authors = ["Matthieu Roux <matthieu.roux@centralesupelec.fr>", "Tyler Becker <Tyler.Becker-1@colorado.edu>", "Qi Heng Ho <qi.ho@colorado.edu>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
POMDPTools = "0.1"
POMDPs = "0.9"
julia = "1.7"
